# THE PASSING MECHANISM FOR ALL PRIMITIVE DATA TYPES IN PYTHON IS PASS BY VALUE
# WHICH MEANS THAT IF YOU CHANGE THE VALUE INSIDE THE METHOD IT DOESNT CHANGE THE ORIGINAL

# WHEN A PARAMETER IS PASSED BY REFERENCE THE VALUE CAN BE CHANGED BY THE METHOD AND IS CHANGED OUTSIDE AND INSIDE THE METHOD

# FUNCTIONS IDEALLY RETURNS A VALUE WITH NO CHANGES TO THE STATE OF THE APPLICATION
# PROCEDURES CHANGES STATE OF THE APPLICATION
# IN PYTHON THIS IS ONLY CONCEPTUAL



from MyClass import MyClass


aMyClass = MyClass()
aMyClass.aString = "Hello World Replacement"
aMyClass.appendAString("!!!")
print(aMyClass.aString)